function [alpha, OD_real, fitresult, gof] = fitline_saturation_intensity_2(ODc, DI, varargin)
%CREATEFIT(TODC,TDI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tODc
%      Y Output: tDI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Mar-2016 18:14:48

%% Process inputs
plotset = {0};
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'plot', plotset = varargin{i+1};
    end
end

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ODc, DI );
% yData = yData(xData<0.5);
% xData = xData(xData<0.5);


% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

%% Plot fit with data.
if plotset{1}
    if length(plotset)==2, axes(plotset{2});
    else figure;
    end
    plot( sort(xData), fitresult(sort(xData)),'r-');
    hold on;
    plot(xData, yData,'b*')
    hold off;
    % Label axes
    xlabel tODc
    ylabel tDI
    grid on
end

%% Prepare output
alpha = -fitresult.p1;
OD_real = fitresult.p2;
