function [outp, fitresult, gof] = fitline_saturation_intensity(DI, ODc, varargin)
%CREATEFIT(DI2,ODC2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : DI2
%      Y Output: ODc2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Mar-2016 15:54:01


%% Process Inputs
DI_threshold = 3e4;
plotset = {0};


for i = 1:2:length(varargin)
    switch varargin{i}
        case 'plot', plotset = varargin{i+1};
        case 'maxDI', DI_threshold = varargin{i+1};
    end
end

%% Procedure
[xDataO, yDataO] = prepareCurveData( DI, ODc );

% Threshold
yData = yDataO(xDataO<= DI_threshold);
xData = xDataO((xDataO<= DI_threshold));

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%% Plot fit with data.

if plotset{1}
    if length(plotset)==2, axes(plotset{2});
    else figure;
    end
    plot( sort(xDataO), fitresult(sort(xDataO)),'r-');
    hold on;
    plot(xData, yData,'b.')
    plot(xDataO,yDataO,'go');
    hold off;
    % Label axes
    xlabel DI
    ylabel OD_c
    grid on
end

%% Collect outputs
outp.Nsat = -1/fitresult.p1;
outp.ODr = fitresult.p2;
outp.sse = gof.sse;
